### ISSUE TITLE
有点懵

### ISSUE THREAD

**Issue by newbiesnote** [NS-Sp4ce/wooyun-drops-tools#1]
![image](https://user-images.githubusercontent.com/46381611/57902391-86e61380-789b-11e9-8f39-05c25a481ac5.png)

**Comment by NS-Sp4ce** [comment]
我这边测试了下，没问题啊，能提供下你出现问题的环境吗？

**Comment by newbiesnote** [comment]
找到原因了，数据库版本问题

**Comment by NS-Sp4ce** [comment]
> 找到原因了，数据库版本问题

好的 那我关了
